server:
  port: ${PORT:8081}
  servlet:
    context-path: /
  request:
    timeout: 5000

spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  application:
    name: gclub
    secret: ${APPLICATION_SECRET_TOKEN}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: ${FLYWAY_MIGRATIONS_PATH}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        timezone: UTC
    sendgrid:
      api-key: ${SENDGRID_API_KEY}
      email: ${SENDGRID_EMAIL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION_MINUTES}